### ISSUE TITLE
pandoc-markdown测试文件 | Geekaholic

### ISSUE THREAD

**Issue by GeekaholicLin** [GeekaholicLin/geekaholiclin.github.io#2]
http://blog.geekaholic.cn/2017/02/19/pandoc-markdown%E6%B5%8B%E8%AF%95%E6%96%87%E4%BB%B6/

**Comment by GeekaholicLin** [comment]
迁移评论框

**Comment by GeekaholicLin** [comment]
手机端官方样式错乱

**Comment by GeekaholicLin** [comment]
:smile: 测试

**Comment by GeekaholicLin** [comment]
:umbrella: 测试

**Comment by GeekaholicLin** [comment]
``` css
<link rel="stylesheet" href="github-markdown.css">
<style>
	.markdown-body {
		box-sizing: border-box;
		min-width: 200px;
		max-width: 980px;
		margin: 0 auto;
		padding: 45px;
	}
</style>
<article class="markdown-body">
	<h1>Unicorns</h1>
	<p>All the things</p>
</article>
<link rel="stylesheet" href="github-markdown.css">
<style>
	.markdown-body {
		box-sizing: border-box;
		min-width: 200px;
		max-width: 980px;
		margin: 0 auto;
		padding: 45px;
	}
</style>
<article class="markdown-body">
	<h1>Unicorns</h1>
	<p>All the things</p>
</article>
<link rel="stylesheet" href="github-markdown.css">
<style>
	.markdown-body {
		box-sizing: border-box;
		min-width: 200px;
		max-width: 980px;
		margin: 0 auto;
		padding: 45px;
	}
</style>
<article class="markdown-body">
	<h1>Unicorns</h1>
	<p>All the things</p>
</article>
```

代码和长度测试
